### ISSUE TITLE
I2C-Transaction has probably failed.

### ISSUE THREAD

**Issue by JohnTordur** [linux-automation/usbsdmux#50]
In my attempt to switch the sdmux to dut mode, and also calling `get,dut,client,host,off`
I get the following error repeatdly:
```
usbsdmux /dev/sg0 host
Traceback (most recent call last):
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/bin/usbsdmux", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/__main__.py", line 76, in main
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/usbsdmux.py", line 112, in mode_host
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/usbsdmux.py", line 77, in mode_disconnect
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/pca9536.py", line 106, in output_values
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/pca9536.py", line 67, in _write_register
  File "/home/john/Source/github.com/pengutronix/usbsdmux/venv/lib64/python3.11/site-packages/usbsdmux-0.2.1-py3.11.egg/usbsdmux/usb2642i2c.py", line 469, in write_to
usbsdmux.usb2642i2c.I2cTransactionFailed: SCSI-Transaction ended with status 2. I2C-Transaction has probably failed.

```

I have loaded the sg kernel module.

I have tried cloning the project, running from source  with venv as specified in the commisioning step.
Furthermore to isolate my distro, I tried running from inside a Docker container running Ubuntu 20 but the error is still there. 

## USB
I tried with to different USB cables, I also tried behind a USB hub, and directly to the USB 2.0 interface, and USB 3.0. Still the same issue.

## System
Here is some info about my system:
```
OS: openSUSE Tumbleweed x86_64 
Kernel: 6.1.12-1-default 
Uptime: 29 days, 5 hours, 6 mins 
Packages: 4355 (rpm), 6 (flatpak), 1 (appimaged) 
Shell: zsh 5.9 
Resolution: 2560x1440, 2560x1440 
DE: Plasma 5.27.1 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 2700X (16) @ 4.000GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 8645MiB / 15917MiB 
```

**Comment by hnez** [comment]
Hi!

did you check if `/dev/sg0` actually corresponds to the USB-SD-Mux you are trying to control?

On my computer I already see two `/dev/sg*` devices before even connecting an USB-SD-Mux:

    leonard@fulladder ~> ls /dev/sg*
    /dev/sg0  /dev/sg1  /dev/sg2

They correspond to two SATA HDDs and a SATA optical drive.

When I connect an USB-SD-Mux it is enumerated as `/dev/sg3`:

```
leonard@fulladder ~> sudo dmesg -w
[28012.240934] usb 1-5.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[28012.240941] usb 1-5.4.1: Product: usb-sd-mux_rev4.0
[28012.240946] usb 1-5.4.1: Manufacturer: Linux Automation GmbH
[28012.240950] usb 1-5.4.1: SerialNumber: 000000000757
[28012.247974] usb-storage 1-5.4.1:1.0: USB Mass Storage device detected
[28012.248196] scsi host10: usb-storage 1-5.4.1:1.0
[28013.258479] scsi 10:0:0:0: Direct-Access     LinuxAut sdmux HS-SD/MMC  2.09 PQ: 0 ANSI: 0
[28013.258726] sd 10:0:0:0: Attached scsi generic sg3 type 0
[28013.259223] sd 10:0:0:0: [sdd] Media removed, stopped polling
[28013.259786] sd 10:0:0:0: [sdd] Attached SCSI removable disk
leonard@fulladder ~> ls /dev/sg*
/dev/sg0  /dev/sg1  /dev/sg2  /dev/sg3
```

The USB-SD-Mux can thus be controlled by entering `usbsdmux /dev/sg3 {get,dut,client,host,off}`.

It's a good idea to not rely on specific `/dev/sg*` device numbers and instead use an udev rule to setup `/dev/usb-sd-mux/id-0000…` links based on the USB-SD-Mux serial numbers.
